### ISSUE TITLE
[retail-ui] Переход на поддержку нескольких версий библиотеки контролов

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1295]
Цель: Дать командам возможность получать фиксы для критичных багов без необходимости обновления до последней текущей версии.

- [x] Облегчить процесс backport'а фиксов из последней версии в LTS
  - [x] Настройка автоматического паблиша старых версий (retail-ui начиная с 0.42.0, react-ui-validations начиная с 0.7.2) -> #1423 
  - [x] Перенос конфигурации CI в репозиторий (#1262) -> c4ec6b1e4
  - [x] Описание процесса (чек-лист того что нужно сделать для выпуска версии с фиксом) -> #1423 и [на wiki](https://wiki.skbkontur.ru/pages/viewpage.action?pageId=291141129)
  - [x] Формализовать критерии для PR определяющие необходимость в backport'е -> [фикс багов в LTS](https://staff.skbkontur.ru/post/5d2f1176fae04d37d469d3a3)
- [ ] Зафиксировать различия между (next, latest, lts, old-version тегами в npm)
- [x] Описать процесс перехода версий из next -> latest -> lts (например как в https://github.com/nodejs/Release) -> [статья про LTS](https://staff.skbkontur.ru/article/5d19cd88fae04d141c302a10)
- [x] Собрать статистику по версиям библиотеки в продуктах (@wKich)
- [x] Опубликовать в стаффе статью (@wKich) [статья про LTS](https://staff.skbkontur.ru/article/5d19cd88fae04d141c302a10)

Возможно что пункты будут добавляться, потому что мог что-то пропустить. Хорошо если получится проделать эту работу до выпуска задачи с кастомизацией.

**Comment by zhzz** [comment]
Как определимся до конца c правилами ведения LTS, можно будет закрывать.
