### ISSUE TITLE
[retail-ui] Темизация-кастомизация. Перевод библиотеки с less на css-in-js

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1318]
Мета таска с описанием плана по задаче темизации.

Общий план:
 - [x] Пометить последний релиз перед выпуском кастомизации как LTS и поддерживать какое-то время выпуская для него только баг фиксы (для упрощения выкатывания фиксов нужно сделать задачку #1295) -> #1423 
 - [x] Выпуск кастомизации -> #1333 
 - ~~(через 2-3 месяца) Кастомизацию через less переменные объявить устаревшей~~
 - [ ] (через 6 месяцев с выпуска кастомизации) Пометить пакет retail-ui deprecated #1578
 - [ ] Отказ от 15-го реакта и перевод retail-ui в статус LTS #1578

Нюанс с поддержкой старых компонентов `ComboBoxOld/DatePickerOld/Kladr`. Так как в компоненты более не добавляется новый функционал, они не будут поддерживать механизм кастомизации с помощью css-in-js. Это выливается в следующие моменты:
- Команды которые используют `@skbkontur/react-ui`, не используют кастомизацию. Поэтому при появлении необходимости в кастомизации им нужно отказаться от использования старых компонентов.
- Команды которые используют `retail-ui`, используют кастомизацию через less. Поэтому при переходе с less на css-in-js им нужно отказаться от использования старых компонентов.
- В остальных случаях предполагается что всё продолжит работать как есть сейчас.

**Comment by step-off** [comment]
**Перевод библиотеки с less на css-in-js. Первая итерация.**

1. В файлах variables.less и variables.flat.less добавляются переменные с атрибутом `@value`, для экспорта значений переменных в виде js-объекта:
  ```
@value brandXLight: @brand_x_light; 
@value brandLight: @brand_light; 
@value brand: @brand; 
@value brandDark: @brand_dark; 
@value brandXDark: @brand_x_dark;
...
  ```

2. Для генерации объекта темы добавляется сущность `ThemeManager`. Объект темы будет представлять собой набор key-value пар, где в качестве key - имя переменной, а value - её значение. Интерфейс объекта темы - `ITheme`. Значения переменных будут подставляться в зависимости от флага `Upgrades.isFlatDesignEnabled()` либо из файла `variables.less`, либо `variables.flat.less`.
У сущности  `ThemeManager` будет 2 публичных метода:
    - `getTheme() => ITheme`, возвращающий объект темы;
    - `overrideTheme(variables: Partial<ITheme>) => ITheme`, переопределяющий переменные и возвращающий новый объект темы.


3. Для каждого компонента будет собран объект стилей. Поля объекта стилей - это методы с соответствующими less-классам именами. Каждый метод принимает объект с переменными `ITheme` и возвращает сгенерированное функцией [css](https://github.com/emotion-js/emotion/tree/master/packages/emotion#css) пакета emotion имя класса. В каждом методе, в функцию css будут передаваться только правила, зависящие от переменных, которые можно переопределить:
```
import { css } from "emotion";
import classes from "./Button.less";
import { ITheme } from "../../lib/ThemeManager";

const jsClasses = {
    root(theme: ITheme) {
        return css`
	  color: ${theme.textColorDefault};
	`;
    },

    warning(theme: ITheme) {
        return css`
	  .${classes.root}:not(.${classes.link}) & {
	    box-shadow: 0 0 0 2px ${theme.warningMain};
	  }
	`;
    },

...
```
  Объект стилей будет жить в отдельном файле `${componentName}.styles.ts`


4. В компоненте, в проп className подставляется вызов соответствующего метода объекта стилей, если в правилах класса используются переменные. В противном случае, как и раньше, подставляется класс из .less файла компонента:
```
import { cx as classNames } from 'emotion';
import classes from './Button.less';
import jsClasses from './Button.styles.ts';
const theme = ThemeManager.getTheme();
...
<div
  className=classNames({
    [jsClasses.root(theme)]: true,
    [jsClasses.warning(theme)]: this.prop.warning,
    [classes.narrow]: this.props.narrow,
    [classes.buttonWithIcon]: !!this.props.icon
  })
/>
...
```
Для комбинирования нескольких классов, сгенерированных [css](https://github.com/emotion-js/emotion/tree/master/packages/emotion#css), вместо пакета classnames будет использоваться аналогичная функция [cx](https://github.com/emotion-js/emotion/tree/master/packages/emotion#cx) из emotion.

5. Плоская версия компонента на выходе имеет практически тот же набор правил, что и обычная версия того же компонента. Отличаются лишь значения правил, зависящих от общих переменных. Поэтому, стили плоской и обычных тем будут приведены к единой структуре, а так как наполнение переменными плоской темы будет происходить в ThemeManager, то можно будет отказаться от файлов со стилями для плоской версии `${componentName}.flat.less`.
Также, из файлов стилей компонентов `${componentName}.less` удалятся правила, в которых используется переменные из variables.less

**Comment by wKich** [comment]
**Вторая итерация**

- Синхронизация свойств default и flat тем #1771
- Перенос оставшихся стилей из less в css-in-js с учетом вложенности классов #1625
