### ISSUE TITLE
[retail-ui] 1.x.x → 2.0.0 tasks

### ISSUE THREAD

**Issue by wKich** [skbkontur/retail-ui#1578]
Пытаюсь собрать более-менее серьезные задачки по тех долгу и не только в библиотеке, которые хорошо бы сделать в рамках 1.x.x, или после 2.0.0. Можно сюда накидать то что я скорее всего забыл/пропустил/не подумал.

## 2.0.0

- [x] Remove custom babel-plugin
- [x] Deprecate old components ~~#1490~~
- [x] css-in-js + code splitting ~~#1568~~, ~~#1556~~, ~~#1530~~
- [x] css → module.css ~~#1572~~
- [x] Update deps, remove unused ~~#1406~~, ~~#1770~~
  - [x] Update react + @types/react ~~#1779~~
  - [x] Sync deps versions between packages (retail-ui/react-ui-validations) ~~#1769~~
  - [x] Обновить react-styleguidist и примеры в доке ~~#1791~~
  - [x] Обновить react-focus-lock и react-transition-group ~~#1861~~
- [x] Remove adapters ~~#1286~~
- [x] Generate docs for TopBar.Dropdown, Modal.Header, etc ~~#1780~~
  - [x] PasswordInput docs
- [x] Inline required react-icons ~~#1781~~
  - [x] remove peerDeps @skbkontur/react-icons
- [x] Actualize vendor typings ~~#1203~~
- [x] Deprecate Kontur-specific components/props ~~#1842~~
  - [x] Deprecate specific/private props from components
  - [x] `Select` remove unused props ~~#1070~~
- [x] Remove React@15.0 support ~~#1841~~
- [x] TSLint → ESLint ~~#1179~~
- [x] TS → Babel@7 ~~#1129~~
  - [x] Remove all deprecated components
  - [ ] ~~Generate proptypes from component interface typings #1128~~
  - [x] Remove flow typings
- [x] сигнатуры onChange (выпилить event, оставить value первым параметром) ~~#1843~~
- [x] Up minimal supported react version to 16.9
- [x] Drop retail-ui support, publish only @skbkontur/react-ui (@zhzz) ~~#1871~~
- [x] \* Add smoke test for @skbkontur/react-ui ~~#1773~~
- [x] Исправить вывод warnings в консоль для некоторых компонентов ~~#915~~
- [x] Less → CSS-in-JS #1625
  - [x] Use FlatTheme as subset of Default Theme ~~#1771~~
- [x] Publish eslint-config (@rustho )
- [x] Экспортировать только ThemeContext и LocaleContext #1894 
- [x] Гайд по миграции с 1.x на 2.0 (@wKich) #1909
- [x] Codemodes #1900
- [x] Reorganize components structure (public/internal) #1772
  - [x] Auto-import components

**Comment by zhzz** [comment]
Доку для TopBar.Dropdown, Modal.Header, etc очень просто сделать. [Достачно](https://github.com/skbkontur/retail-ui/blob/master/packages/retail-ui/.styleguide/helpers.js#L38) вынести компонент в отдельную директорию и снабдить README.md. После этого они появятся в styleguidist.

**Comment by zhzz** [comment]
Еще нужно снова пройтись Prettier'ом и настроить форматирование кода на коммит.

**Comment by zhzz** [comment]
Есть желание избавиться от flow-тайпингов. За ними никто не следит, они неактуальны и, вероятно, мало кому нужны.

**Comment by wKich** [comment]
@Eazymov, вы ещё используйте flow? Как ты смотришь на то чтобы перетащить тайпинги из либы в flow-typed репу?

**Comment by Eazymov** [comment]
> @Eazymov, вы ещё используйте flow? Как ты смотришь на то чтобы перетащить тайпинги из либы в flow-typed репу?

Ок, могу заняться этим в выходные
