### ISSUE TITLE
[react-ui] 2.0.0 → 2.X.0 tasks

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#1962]
## Enchantment
- [x] #2945
- [ ] Добавить `eslint` плагин `@skb-kontur/react-ui/recomended` #1895
- [ ] Popup/DropdownContainer #913
  - [ ] Disabled `useWrapper` prop for `Popup` by default
- [ ] Переименовать репозиторий в react-ui #1881 
- [ ] react-ui + telemetry #1555

## Tech Debt
- [ ] Интеграционные тесты с @skbkontur/react-ui-addons
- [ ] Smoke tests for documentaion #1298
- [ ] Setup lint-staged precommit hook
  - [ ] Setup CI formatting check #1009
- [ ] Extract jest config from package.json #1178
- [ ] Unit tests with various react versions
- [ ] Update prettier + format codebase #1794 
- [ ] Sync versions react-ui, react-ui-validations
- [ ] Allow work components in React.StrictMode
- [ ] Perfomance, why-did-you-update
- [ ] Refactor components to use React.Hooks API
- [ ] Move react-ui-validation docs to styleguidist
- [ ] Поддержка React 17
  - [ ] Избавление от [unsafe lifecycles](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)
  - [ ] Избавление от [legacy Context API](https://reactjs.org/docs/legacy-context.html)

**Comment by halex2005** [comment]
Почему-то пункт "Поддержка React 17" последний. Надеюсь, что это из серии "last but not least" и эта поддержка пробежит вперед других задачек 🥇

**Comment by zhzz** [comment]
@halex2005 На самом деле в React 17 старое api не удалили и, вроде бы, у библиотеки не должно быть проблем с его поддержкой. Но за те задачки мы в любом случае скоро планируем взяться, да.

**Comment by dzekh** [comment]
Переехала в ютрек
