### ISSUE TITLE
[react-ui] Старт поддержки мобильных

### ISSUE THREAD

**Issue by dzekh** [skbkontur/retail-ui#1963]
[Черновик аналитики](https://docs.google.com/document/d/1xgYgL102ZjvMhS5pz9qtWcD2zmwHOl1Lww1AFsZ9Nlw/edit?usp=sharing) для старта поддержки мобильных.

## Инфра
- [x] Определить брекпоинты, как и где мы будем их хранить, и возможно ли будет их переопределять
- [x] Определить как мы будем переключать компоненты в мобильный вид, только по брекпоинтам или как-то еще
- [x] Определить какие версии каких мобильных платформ и браузеров мы будем поддерживать
- [x] Описать в общих чертах требования к поведению компонентов на мобильных, какие будут меняться какие нет. 
- [x] Определить будут ли в темах жить и переопределяться переменные для мобилок. Например разные внутренние отступы компонентов или размеры шрифтов.

## Bugs

- [x] Не удаляются значения через экранную клавиатуру CurrencyInput, FxInput #1523, #1865
- [x] Нельзя удалить значения из поля ввода даты — нет клавиатуры #1679
- [x] Неадекватно работает Tooltip на IOS #1495
- [x] Не работает скролл календаря DatePicker. #1619

## Enchantment

- [x] Если в поле можно вводить только цифры — выводить клавиатуру с цифрами. Возможность передачи type="number"  #1678, #675
- [x] Уменьшать внутренние отступы модалки при отображении на мобильных #1491
