### ISSUE TITLE
[react-ui] 3.0.0

### ISSUE THREAD

**Issue by zhzz** [skbkontur/retail-ui#2123]
Список задач на 3.0.0.

- [x] Доработки по кастомизации
  - [x] 8px тема
    - [x]  Допилить тесты #2071
    - [x]  Вторая очередь переменных #1733
    - [ ]  Сделать чтоб работала везде fontFamilyCompensationBaseline
    - [x]  Заменить иконки-стрелки у инпутов комбобокса и кнопок селекта и прочих
    - [x]  Проверить и исправить кликабельные области иконок
    - [x]  Включить новую тему по умолчанию в 3.0
  - [ ]  Все issue с лейблом [`customization`](https://github.com/skbkontur/retail-ui/issues?q=is%3Aissue+is%3Aopen+label%3Acustomization)
  - [x] Удаление/депрекейт старых переменных
- [ ] Поддержка мобильных
  - [x] Проброс пропов #2107 
  - [ ] Пока собирается аналитика по #1963, можно хоть как-то позакрывать все issue с лейблом [`mobile`](https://github.com/skbkontur/retail-ui/issues?q=is%3Aissue+is%3Aopen+label%3Amobile)
- [ ]  Поддержка [Strict Mode](https://reactjs.org/docs/strict-mode.htm) (@lossir)
- [x] Обновление зависимостей
- [x] Удаление Контур-специфичных компонентов
  - [ ] Пофиксить связанные с ними issue в аддонах
- [x] Кнопки
  - [x] Поменять состояние loading #2133 
  - [x] Отказаться от прозрачного фона? (плоская тема, #1513, https://t.me/react_ui/7082 )
  - [x] Переверстать стрелки [по-проще](https://codesandbox.io/s/react-ui-template-9qeb9?file=/src/arrows.css)

**Comment by dzekh** [comment]
Посмотреть задачи [из тех что не успели в 2.0](https://github.com/skbkontur/retail-ui/issues/1962).
