### ISSUE TITLE
[FileUploader] Добавить размеры в FileUploader IF-626

### ISSUE THREAD

**Issue by ant-d-skb** [skbkontur/retail-ui#2959]
- [x] добавить стандартные размеры в компонент;
- [x] убрать минимальную ширину компонента, сделать обрезку текста, который не помещается в компонент;
- [x] добавить border-radius из стайлгайда;
- [x] привести цвет текста в контроле в соответствие с гайдами;
- [x] изменить отступ между размером файла и именем;
- [ ] поменять старую иконку Upload на новую;

**Comment by JackUait** [comment]
Привет! Правильно понимаю, что это ишью связано с [этим](https://kontur.slack.com/archives/C013HTCE18Q/p1657626614033429) обращением?

**Comment by ant-d-skb** [comment]
Привет!
Да, создал ишью, вот создаю ПР. Мне бы прав немного отсыпать
 
Антонов Денис
 

От: Евгений Пятков
Отправлено: 21 июля 2022 г. в 13:13
Кому: skbkontur/retail-ui
Копия: Антонов Денис Михайлович; 
Author
Тема: Re: [skbkontur/retail-ui] Добавить размеры в FileUploader (Issue #2959)

 



Привет! Правильно понимаю, что это ишью связано с 
этим обращением?
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/skbkontur/retail-ui/issues/2959#issuecomment-1191182267",
"url": "https://github.com/skbkontur/retail-ui/issues/2959#issuecomment-1191182267",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JackUait** [comment]
А можешь в профиле на стаффе добавить свой ник на гитхабе? По идее система должна будет выдать права

**Comment by ant-d-skb** [comment]
Добавил
 
Антонов Денис
 

От: Евгений Пятков
Отправлено: 21 июля 2022 г. в 13:32
Кому: skbkontur/retail-ui
Копия: Антонов Денис Михайлович; 
Author
Тема: Re: [skbkontur/retail-ui] Добавить размеры в FileUploader (Issue #2959)

 



А можешь в профиле на стаффе добавить свой ник на гитхабе? По идее система должна будет выдать права
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/skbkontur/retail-ui/issues/2959#issuecomment-1191200364",
"url": "https://github.com/skbkontur/retail-ui/issues/2959#issuecomment-1191200364",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
